// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_qpcCUjOAsFH2ufdhK-hJpEhY2aQi0sI',
    appId: '1:1071752784061:web:28abeb2d3ea36b529f6fd4',
    messagingSenderId: '1071752784061',
    projectId: 'chat-app-5f5f2',
    authDomain: 'chat-app-5f5f2.firebaseapp.com',
    storageBucket: 'chat-app-5f5f2.firebasestorage.app',
    measurementId: 'G-DZJFQP03DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5JCuPCZkFIcQMru6D05o12kgSnYJ7tto',
    appId: '1:1071752784061:android:00fb35e06416c6839f6fd4',
    messagingSenderId: '1071752784061',
    projectId: 'chat-app-5f5f2',
    storageBucket: 'chat-app-5f5f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrG938dxEJ-_ztWXjn3DTHshIHNFRbkdM',
    appId: '1:1071752784061:ios:6ae74b9a5eec95139f6fd4',
    messagingSenderId: '1071752784061',
    projectId: 'chat-app-5f5f2',
    storageBucket: 'chat-app-5f5f2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrG938dxEJ-_ztWXjn3DTHshIHNFRbkdM',
    appId: '1:1071752784061:ios:6ae74b9a5eec95139f6fd4',
    messagingSenderId: '1071752784061',
    projectId: 'chat-app-5f5f2',
    storageBucket: 'chat-app-5f5f2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_qpcCUjOAsFH2ufdhK-hJpEhY2aQi0sI',
    appId: '1:1071752784061:web:920289eb8dad0a369f6fd4',
    messagingSenderId: '1071752784061',
    projectId: 'chat-app-5f5f2',
    authDomain: 'chat-app-5f5f2.firebaseapp.com',
    storageBucket: 'chat-app-5f5f2.firebasestorage.app',
    measurementId: 'G-H1ZC6QE08M',
  );
}
